services:
  mongo:
    image: mongo:7.0
    ports:
      - "27500:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always

volumes:
  mongodata:
    driver: local
